version: "3"
services:

  orders:
    image: roktkalcic/ordersapi:v1.3
    ports:
      - 8080:8080
    networks:
      - my-network

  sensor:
    image: roktkalcic/sensorapi:v1.1
    ports:
      - 8000:8000
    networks:
      - my-network

  navbar:
    image: roktkalcic/navbar:v1.1
    ports:
      - 3333:3333
    networks:
      - my-network
    # Add additional configuration options as needed

  host:
    image: roktkalcic/host:v1.1
    ports:
      - 3200:3200
    networks:
      - my-network
    # Add additional configuration options as needed
  
  mobile-api-gateway:
    image: roktkalcic/mobile-api-gateway:v1.3
    ports:
      - 4000:4000
    networks:
      - my-network
    # Add additional configuration options as needed

  web-api-gateway:
    image: roktkalcic/web-api-gateway:v1.1
    ports:
      - 3000:3000
    networks:
      - my-network
    # Add additional configuration options as needed


networks:
  my-network:
    driver: bridge
